
[cursor]
style = "Beam"

[font]
size = 11

[font.normal]
family = "JetBrains Mono"

[scrolling]
history = 40000
multiplier = 10

[selection]
semantic_escape_chars = ",â”‚`|:=\"' ()[]{}<>-"

[window.padding]
x = 12
y = 12

[general]
import = ["~/personal/dotfiles/alacritty/shared/theme.toml"]
